FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY doorbell_pub.py ./

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

CMD ["python", "-u", "src/doorbell_pub.py"]